# Generated by Django 5.0.9 on 2026-09-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="provider",
            field=models.CharField(
                choices=[
                    ("simulated", "Simulated (test rules, no real processor)"),
                    ("razorpay", "Razorpay"),
                ],
                default="simulated",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="provider_order_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="transaction",
            name="provider_payment_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("card", "Card"),
                    ("upi", "UPI"),
                    ("netbanking", "Netbanking"),
                    ("wallet", "Wallet"),
                ],
                max_length=20,
            ),
        ),
    ]
